config/routes.rb
CopyQiita::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'welcome#index'
  get 'items', to: 'items#index'
  resources :items, only: [ :show ]

  namespace :user do
    resources :items, except: [ :show ]
    resources :stocks, only: [ :index ]
  end

  post '/user/item/preview', to: 'user/items#preview'

  with_options controller: 'user/stocks' do |s|
    s.post 'user/item/:item_id/stocks', to: :create, as: :stock_create
    s.delete 'user/item/:item_id/stocks', to: :destroy, as: :stock_destroy
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :stocks, dependent: :destroy
  has_many :stocking_users, through: :stocks, source: :user

  validate :title, presence: true
  validate :contents, presence: true

  def stocked?
    if self.user.stocks.find_by_item_id(self.id)
      true
    end
  end

  def mine?(user)
    return false unless user
    self.user.id == user.id
  end
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [ :github ]

  has_many :items
  has_many :stocks
  has_many :stocked_items, through: :stocks, source: :item

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.nickname = auth.info.nickname
      user.image = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [ :show ]

  def index
    @items = Item.page(params[:page])
  end

  private

    def set_item
      @item = Item.find(params[:id])
    end
end

app/controllers/user/items_controller.rb
class User::ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [ :show, :edit, :update, :destroy ]

  def index
    @items = current_user.items.page(params[:page])
  end

  def new
    @item = current_user.items.build
  end

  def preview
    @title = params[:title]
    @contents = params[:contents]
    respond_to do |format|
      format.js { render 'preview' }
    end
  end

  def create
    @item = current_user.items.build(item_params)
    respond_to do |format|
      if @item.save
        flash[:notice] = '投稿を作成しました。'
        format.html { redirect_to user_item_path(@item) }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        flash[:notice] = '投稿を更新しました。'
        format.html { redirect_to item_path @item }
        format.json { render 'user/show', status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      flash[:notice] = '投稿を削除しました。'
      format.html { redirect_to user_items_path }
      format.json { head :no_content }
    end
  end

  private

    def set_item
      @item = current_user.items.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:title, :contents)
    end
end

app/controllers/user/stocks_controller.rb
class User::StocksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [ :create, :destroy ]

  def index
    @stocks = current_user.stocks
  end

  def create
    @stock = current_user.stocks.build(item_id: params[:item_id])
    respond_to do |format|
      if @stock.save
        @item = Item.find(params[:item_id])
        format.js
      else
        format.js { redirect_to user_items_path(@item) }
      end
    end
  end

  def destroy
    @stock = current_user.stocks.find_by_item_id(params[:item_id])
    @stock.destroy
    @item = Item.find(params[:item_id])
    respond_to do |format|
      format.js
    end
  end

  private

    def set_item
      @item = Item.find(params[:item_id])
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: :github) if is_navigational_format?
    else
      session['devise.github_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    return '' unless text
    unless @markdown
      renderer = Redcarpet::Render::HTML.new
      @markdown = Redcarpet::Markdown.new(renderer)
    end
    @markdown.render(text).html_safe
  end
end

app/helpers/items_helper.rb
module ItemsHelper

  def gravatar_for(user)
    image_tag(user.image, alt: user.nickname, size: '24x24', class: 'gravatar')
  end

end

app/helpers/user/items_helper.rb
module User::ItemsHelper
end

app/helpers/user/stocks_helper.rb
module User::StocksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_item.html.haml
%tr
  %td
    = gravatar_for item.user
    = item.user.nickname
  %td
    = link_to item.title, item
  %td
    = distance_of_time_in_words_to_now item.created_at
  %td
    = item.stocks.size

app/views/items/index.html.haml
%h1 すべての投稿

- if user_signed_in?
  .user-actions
    %p
      = link_to 'Create New Item', new_user_item_path

%table.table
  %thead
    %tr
      %th 投稿ユーザー
      %th タイトル
      %th 投稿日
      %th ストック数
  %tbody
    = render @items


= paginate @items

app/views/items/show.html.haml
.row
  .col-md-12
    = render 'shared/item_header', item: @item

  .container
    .row
      .col-md-12
        .contents
          = simple_format markdown(@item.contents)

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{'data-toggle' => 'collapse',
                                      'data-target' => '#header-navbar-collapse',
                                      'type' => 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'CopyQiita', root_path, class: 'navbar-brand'
    #header-navbar-collapse.collapse.navbar-collapse
      %form.navbar-form.navbar-left{role: 'search'}
        .form-group
          %input.form-control{type: 'text', placeholder: 'Search'}
        %button.btn.btn-default{type: 'button'} 検索
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{'data-toggle' => 'dropdown',
                               'href' => '#'}
              新規作成
              %span.caret
            %ul.dropdown-menu{role: 'menu'}
              %li
                %a{href: '#'} 投稿する
              %li
                %a{href: '#'} 下書き一覧
          %li
            = link_to 'ストック一覧', user_stocks_path
          %li
            %a{href: '#'} お知らせ数
          %li.dropdown
            %a.dropdown-toggle{'data-toggle' => 'dropdown',
                               'href' => '#'}
              Profile
              %span.caret
            %ul.dropdown-menu{role: 'menu'}
              %li
                = link_to 'マイページ', user_items_path
              %li
                = link_to '設定', edit_user_registration_path
              %li.divider
              %li
                - if user_signed_in?
                  = link_to 'Sign out', destroy_user_session_path, method: :delete
                - else
                  = link_to 'Sign in with Github', user_omniauth_authorize_path(:github)
        - else
          %li
            = link_to 'Sign in with Github', user_omniauth_authorize_path(:github)

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .row
      .col-sm-12
        %div{ class: "alert alert-#{name == :notice ? "success" : "danger"}"}
          %button.close{ type: 'button', 'data-dismiss' => 'alert', 'aria-label' => 'Close'}
            %span{ 'area-hidden' => 'true' }
              %i.glyphicon.glyphicon-remove
          = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title CopyQiita
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .header
      = render 'layouts/header'

    .container-fluid
      = render :partial => 'layouts/messages'
      .row
        .col-sm-12.main
        = yield

app/views/shared/_item_header.html.haml
.item-header
  .container
    .row
      .col-sm-9
        .item-header-main
          %h1=item.title

          .author-info
            = gravatar_for item.user
            .author-name
              = "#{item.user.nickname} が #{item.created_at}に投稿しました。"
          - if item.mine?(current_user)
            .my-item-actions
              = link_to "投稿を編集する", edit_user_item_path(item), class: "btn btn-default"

      .col-md-3
        #stock-action
          = render 'user/stocks/stock_btn'

app/views/user/items/_form.html.haml
.row
  .col-sm-6
    = simple_form_for [ :user, @item ], html: { class: 'form-horizontal' } do |f|
      .form-inputs
        = f.input :title, input_html: { class: 'form-control js-update-preview' }
        = f.input :contents, input_html: { class: 'form-control js-update-preview', rows: 20 }
        = f.button :submit, class: 'btn btn-primary'

  #item-preview.col-sm-6
    %h2#preview_title.preview-header= @item.title
    #preview_contents.preview-contents= simple_format( markdown(@item.contents) )

app/views/user/items/_item.html.haml
%tr
  %td
    = link_to item.title, edit_user_item_path(item)
  %td
    = link_to 'Delete', user_item_path(item), method: :delete, class: "btn btn-danger",
      data: { confirm: 'Are you sure?' }

app/views/user/items/edit.html.haml
.container
  .row
    = render 'form'

app/views/user/items/index.html.haml
%h2="#{current_user.nickname}の投稿一覧"

%table.table
  %thead
    %tr
      %th タイトル
      %th
  %tbody
    = render @items

= paginate @items

= link_to 'Create New Item', new_user_item_path

app/views/user/items/new.html.haml
= render 'form'

= link_to 'Back', root_path

app/views/user/items/preview.js.erb
$('#preview_title').html("<%= j(@title)%>");
$('#preview_contents').html("<%= j(simple_format(markdown(@contents)) )%>");

app/views/user/stocks/_stock.html.haml
%tr
  %td
    = gravatar_for stock.item.user
    = stock.item.user.nickname
  %td
    = link_to stock.item.title, item_path(stock.item)

app/views/user/stocks/_stock_btn.html.haml
.stock-info
  .stock-num
    = @item.stocks.size
  .stock-label ストック

- if user_signed_in?
  -if  @item.stocked?
    = link_to 'ストック解除', stock_destroy_path(@item), method: :delete, remote: true, class: "btn btn-default btn-block stocked"
  - else
    = link_to 'ストックする', stock_create_path(@item), method: :post, remote: true, class: "btn btn-default btn-block"

app/views/user/stocks/create.js.erb
$('#stock-action').html("<%= j(render 'user/stocks/stock_btn') %>");

app/views/user/stocks/destroy.js.erb
$('#stock-action').html("<%= j(render 'user/stocks/stock_btn') %>");

app/views/user/stocks/index.html.haml
%h1 ストック一覧
%table.table
  %thead
    %tr
      %th 投稿者
      %th タイトル
  %tbody
    = render @stocks

app/views/welcome/index.html.haml
%h1 Welcome To Qiita copy app

- if user_signed_in?
  %p
    ="#{current_user.nickname} さんこんにちは!"
  %p
    = link_to 'Create New Item', new_user_item_path
  %p
    = link_to '記事一覧を見る', items_path
- else
  %p
    投稿するにはログインが必要です。
    = link_to 'Sign in with Github', user_omniauth_authorize_path(:github)